### ISSUE TITLE
playsound error

### ISSUE THREAD

**Issue by SoftologyPro** [TemporalLabsLLC-SOL/TemporalPromptGenerator#2]
After installing, when I run TemporalPromptEngine.py I get this error

```
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:01<00:00,  5.53it/s]
['4K UHD - The standard for most content, from streaming to cinema - PROS: Sharp, available on most devices - CONS: Large file sizes, outdated by 8K', '8K UHD - The new cutting-edge standard for displays and high-end cinema - PROS: Extreme clarity and sharpness - CONS: Large file sizes, high hardware requirements', '12K Cinema - Experimental format for cinema production, offering unparalleled clarity - PROS: Stunning for huge screens - CONS: Overkill for most uses, massive file sizes', '1440p QHD - Popular for gaming and mid-range monitors, offering a good balance - PROS: Sharp and faster processing than 4K - CONS: Not 4K', '5.3K - Specialized use in action cameras and some professional equipment - PROS: Great for high-speed recording - CONS: Niche, limited adoption']
['PROFESSIONAL - ARRI - Alexa LF (2020) - PROS: Large format digital cinema, beautiful image quality - CONS: Expensive, heavy', 'PROFESSIONAL - RED - Komodo 6K (2020) - PROS: Compact, 6K resolution, affordable for RED standards - CONS: Limited dynamic range compared to higher-end models', 'PROFESSIONAL - Sony - FX9 (2020) - PROS: Full-frame digital cinema, excellent autofocus - CONS: Expensive, complex to use', 'PROFESSIONAL - Canon - EOS C500 Mark II (2020) - PROS: Full-frame digital cinema, superb color science - CONS: Expensive', 'PROFESSIONAL - Blackmagic - URSA Mini Pro 12K (2020) - PROS: 12K resolution, affordable for high-end cinema - CONS: Large files, requires powerful hardware for editing', 'PROFESSIONAL - Panasonic - Lumix S1H (2020) - PROS: Full-frame mirrorless camera with excellent video features - CONS: Expensive for mirrorless, limited for high-end cinema', 'PROFESSIONAL - Sony - α7S III (2020) - PROS: Excellent low-light performance, compact, 4K video - CONS: Limited for high-end cinema', 'PROFESSIONAL - Canon - EOS R5 (2020) - PROS: 8K video, excellent autofocus - CONS: Overheating issues with extended use', 'PROFESSIONAL - DJI - Ronin 4D (2021) - PROS: Integrated gimbal and cinema camera, excellent stabilization - CONS: Expensive, limited lens options', 'CONSUMER - GoPro - HERO10 Black (2021) - PROS: Great for action shots, 5.3K video, waterproof - CONS: Limited low-light performance', 'PROFESSIONAL - Sony - FX6 (2020) - PROS: Compact full-frame cinema camera, great for indie filmmakers - CONS: Limited dynamic range compared to larger cinema cameras', 'PROFESSIONAL - RED - V-Raptor ST (2021) - PROS: 8K resolution, excellent image quality - CONS: Expensive, complex to operate', 'PROFESSIONAL - Canon - EOS C70 (2020) - PROS: Compact digital cinema camera, excellent image quality - CONS: Limited lens options', 'PROFESSIONAL - Nikon - Z9 (2021) - PROS: 8K video, excellent image quality - CONS: Expensive, limited lens options for cinema', 'PROFESSIONAL - Panasonic - Lumix GH6 (2022) - PROS: Great for video production, 4K 120fps - CONS: Micro four-thirds sensor limits low-light performance']
Traceback (most recent call last):
  File "D:\Tests\Temporal Prompt Engine\TemporalPromptGenerator\WINDOWS\TemporalPromptEngine.py", line 5030, in <module>
    class MultimediaSuiteApp:
  File "D:\Tests\Temporal Prompt Engine\TemporalPromptGenerator\WINDOWS\TemporalPromptEngine.py", line 6641, in MultimediaSuiteApp
    from playsound import playsound
ModuleNotFoundError: No module named 'playsound'
The system cannot find the path specified.
```

Trying `pip install playsound` gives

```
Collecting playsound
  Downloading playsound-1.3.0.tar.gz (7.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "D:\Tests\Temporal Prompt Engine\TemporalPromptGenerator\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\Tests\Temporal Prompt Engine\TemporalPromptGenerator\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\Tests\Temporal Prompt Engine\TemporalPromptGenerator\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Jason\AppData\Local\Temp\pip-build-env-lci5u8z4\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\Jason\AppData\Local\Temp\pip-build-env-lci5u8z4\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\Jason\AppData\Local\Temp\pip-build-env-lci5u8z4\overlay\Lib\site-packages\setuptools\build_meta.py", line 516, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Jason\AppData\Local\Temp\pip-build-env-lci5u8z4\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "D:\Python\lib\inspect.py", line 1139, in getsource
          lines, lnum = getsourcelines(object)
        File "D:\Python\lib\inspect.py", line 1121, in getsourcelines
          lines, lnum = findsource(object)
        File "D:\Python\lib\inspect.py", line 958, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by SoftologyPro** [comment]
OK, to fix this, you need to use

```
pip install --upgrade wheel
pip install playsound
```

Those need to be run after installing requirements.txt

**Comment by SoftologyPro** [comment]
Next issue.  After CogVideoX is cloned...

```
---------------------------
Error
---------------------------
Failed to create virtual environment or install dependencies: Command '['py', '-3.12', '-m', 'venv', 'D:\\Tests\\Temporal Prompt Engine\\TemporalPromptGenerator\\WINDOWS\\CogVideo\\inference\\gradio_composite_demo\\CogVx']' returned non-zero exit status 103.
---------------------------
OK   
---------------------------
```

Does it need to have version 3.12?  If that is removed it should work for other versions.  I have 3.10 to work with hundreds of other ML/AI scripts.

```
Python 3.12 not found!
Installed Pythons found by py Launcher for Windows
 (venv) *
 -3.10-64

Requested Python version (3.12) not installed, use -0 for available pythons
```

**Comment by SoftologyPro** [comment]
My apologies.  I was installingg via pip install -r requirements rather than setup.py.
The 3.12 version issue still exists.  I will raise a new issue for that.
